CREATE TABLE IF NOT EXISTS clicks (
    id SERIAL PRIMARY KEY,
    clicked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mailer_id  TEXT NOT NULL REFERENCES mailers(id),
) PARTITION BY RANGE (clicked_at);


CREATE TABLE IF NOT EXISTS mailers (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);