# Use the official Node.js image
FROM public.ecr.aws/docker/library/node:18-alpine

# Set the working directory
WORKDIR /app

COPY package.json ./

# Install pnpm
RUN npm install 

# Copy the rest of the application code
COPY . .

ENV HOSTNAME "0.0.0.0"
# Expose the port the client runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]
